source:
  server: "127.0.0.1,50026"
  database: "prd-dia-asql-db-procure-dirc"
  username_env: "SOURCE_DB_PRD_USER"
  password_env: "SOURCE_DB_PRD_PASSWORD"
  schema: "dirc_prd"

target:
  server: "localhost,1400"
  database: "dirc"
  username_env: "TARGET_DB_USER"
  password_env: "TARGET_DB_PASSWORD"
  schema: "dirc_prd_0924"

options:
  batch_size: 1000
  clear_target_tables_first: true
  ecrypt: false
  trust_server_certificate: true
  driver: "ODBC Driver 18 for SQL Server"
  fast_executemany: false

mode: copy_all_from_schema

exclude_tables:
  - DCM_UPLOAD

