source:
  server: "127.0.0.1,50025"
  database: "dev-dia-asql-db-procure-dirc-int"
  username_env: "SOURCE_DB_USER"
  password_env: "SOURCE_DB_PASSWORD"
  schema: "dirc_int"

target:
  server: "localhost,1400"
  database: "dirc"
  username_env: "TARGET_DB_USER"
  password_env: "TARGET_DB_PASSWORD"
  schema: "dirc_i_514"

options:
  batch_size: 1000
  clear_target_tables_first: true
  ecrypt: false
  trust_server_certificate: true
  driver: "ODBC Driver 18 for SQL Server"
  fast_executemany: false

tables:
  - AIR_FREIGHT_LANE
  - AIR_FREIGHT_MASTER_DATA_PORT
  - AIR_FREIGHT_MASTER_DATA_VALUE
  - BAF_INDEX
  - BAF_INDEX_CONTRACT
  - BAF_INDEX_UPDATE_HISTORY
  - BAF_INDEX_UPLOAD_HISTORY
  - BID_SHEET
  - BID_SHEET_LANE_OVERLAND_FTL
  - CONTEXT_HELP
  - CONTRACT
  - CONTRACT_REFERENCE_INDEX
  - DCM_UPLOAD
  - EXCHANGE_RATE
  - EXCHANGE_RATE_ICR_MAPPING
  - EXCHANGE_RATE_UPLOAD
  - EXCHANGE_RATE_YTD_MONTHLY
  - EXCHANGE_RATE_YTD_MONTHLY_UPLOAD
  - FEEDBACK
  - flyway_schema_history
  - FOOTNOTE
  - GLOBAL_ZONING
  - ICR_RESULT
  - ICR_UPDATE
  - MATERIAL_MIX
  - OVERLAND_FREIGHT_FTL_LANE
  - OVERLAND_FREIGHT_FTL_STOP
  - OVERLAND_FREIGHT_LTL_LANE
  - OVERLAND_FREIGHT_MASTER_DATA_VALUE
  - PACKAGING_INDEX
  - PACKAGING_INDEX_CONTRACT_REVIEW_PERIOD
  - PACKAGING_INDEX_UPDATE_HISTORY
  - PACKAGING_INDEX_UPDATE_HISTORY_REVIEW_PERIODS
  - PACKAGING_LANE
  - PACKAGING_MASTER_DATA_VALUE
  - PLANNING_ASSUMPTION_LSP_TOP_LANE_PER_MONTH
  - PLANNING_ASSUMPTION_REPORT
  - PLANNING_ASSUMPTION_REPORT_AIR_LANE_CONTRACT
  - PLANNING_ASSUMPTION_REPORT_LANE_LSP
  - PLANNING_ASSUMPTION_REPORT_SEA_LANE_CONTRACT
  - PLANNING_ASSUMPTION_REPORT_TOP_LANE
  - PLANNING_ASSUMPTION_REPORT_TOP_LANE_PLACE_ZONE
  - PLANNING_ASSUMPTION_TOP_LANE_UPDATE
  - PLANT_INFO
  - RATE_CARD_UPLOAD_SESSION
  - RAW_MATERIAL
  - SEA_FREIGHT_LANE
  - SEA_FREIGHT_MASTER_DATA_PORT
  - SEA_FREIGHT_MASTER_DATA_VALUE
  - SEA_FREIGHT_VOLUME_UPLOAD
  - SEA_FREIGHT_VOLUMES
  - SUPPLIER
  - SYSTEM_SETTINGS
  - WAREHOUSE_CATALOG
  - WAREHOUSE_MASTER_DATA_VALUE
  - WAREHOUSING_LANE

